const test=require('node:test'),assert=require('node:assert/strict'),ExcelJS=require('exceljs');
const {loadTs}=require('./load-ts.cjs');
const base={source:'direct',status:'waiting_payment',insurance_duration_years:1,calculated_age:25,calculated_price:525,created_at:'2026-09-17T10:00:00Z',client:{first_name:'Exemple',last_name:'Test'}};
const rows=[{...base,id:'own',request_code:'OWN',assigned_agent_id:'agent-a'},{...base,id:'other',request_code:'OTHER',assigned_agent_id:'agent-b'},{...base,id:'free',request_code:'FREE',assigned_agent_id:null}];
function database(tables,cap=1,failure=null){return {from(table){let predicates=[];let start=0,end=Infinity;const q={select(){return q},order(){return q},eq(k,v){predicates.push(r=>r[k]===v);return q},is(k,v){return q.eq(k,v)},in(k,values){predicates.push(r=>values.includes(r[k]));return q},or(value){const conditions=value.split(',').map(x=>{const [key,op,...v]=x.split('.');return r=>op==='is'?r[key]===null:r[key]===v.join('.')});predicates.push(r=>conditions.some(c=>c(r)));return q},range(a,b){start=a;end=Math.min(b,a+cap-1);return q},then(resolve){return Promise.resolve({data:failure?null:(tables[table]||[]).filter(r=>predicates.every(p=>p(r))).slice(start,end+1),error:failure?{message:failure}:null}).then(resolve)}};return q}}}
async function exported(role='agent',params='',userId='agent-a'){
 const {GET}=loadTs('app/api/admin/exports/dossiers/route.ts',{'@/lib/supabase/server':{createServerSupabaseClient:async()=>({auth:{getUser:async()=>({data:{user:userId?{id:userId,app_metadata:{role}}:null},error:null})}})},'@/lib/supabase/service':{createServiceClient:()=>database({insurance_requests:rows})}});
 const response=await GET(new Request('http://test.local/api/admin/exports/dossiers?'+params));
 if(response.status!==200)return {status:response.status,codes:[]};
 const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(Buffer.from(await response.arrayBuffer()));const codes=[];workbook.getWorksheet(1).eachRow((r,i)=>{if(i>1)codes.push(r.getCell(1).value)});return {status:200,codes};
}
test('audit export: agent scope survives a server cap and excludes another agent',async()=>assert.deepEqual(await exported(),{status:200,codes:['OWN','FREE']}));
test('audit export: agent cannot bypass scope using an arbitrary agent filter',async()=>assert.deepEqual((await exported('agent','agent=agent-b')).codes,['OWN','FREE']));
test('audit export: my and unassigned filters match the authorized list',async()=>{assert.deepEqual((await exported('agent','agent=me')).codes,['OWN']);assert.deepEqual((await exported('agent','agent=unassigned')).codes,['FREE']);});
test('audit export: admin can export all pages or select another agent',async()=>{assert.deepEqual((await exported('admin')).codes,['OWN','OTHER','FREE']);assert.deepEqual((await exported('admin','agent=agent-b')).codes,['OTHER']);});
test('audit export: anonymous and partner accounts are rejected',async()=>{assert.equal((await exported('agent','',null)).status,401);assert.equal((await exported('partner')).status,403);});
const {normalizeIban,isValidIban}=loadTs('lib/validation/iban.ts');
test('audit bank: real checksum and country length reject invalid or altered IBAN',()=>{assert.equal(isValidIban(normalizeIban('tr33 0006 1005 1978 6457 8413 26')),true);for(const value of ['ABC','TR340006100519786457841326','TR33000610051978645784132','ZZ330006100519786457841326'])assert.equal(isValidIban(value),false);assert.equal(isValidIban('GB82WEST12345698765432'),true);});
test('audit bank: invalid IBAN is rejected before any database write',async()=>{const {PUT}=loadTs('app/api/admin/settings/bank/route.ts',{'@/lib/auth/requireApiRole':{requireApiRole:async()=>({success:true,role:'admin',user:{id:'admin'}})},'@/lib/supabase/service':{createServiceClient:()=>{throw Error('Database must not be accessed')}}});assert.equal((await PUT(new Request('http://test.local',{method:'PUT',body:JSON.stringify({beneficiary:'Exemple',bankName:'Exemple',iban:'ABC'})}))).status,400);});
async function summary(requests,activities=[],failure=null){const {getNotificationSummary}=loadTs('lib/admin/getNotificationSummary.ts',{'@/lib/supabase/service':{createServiceClient:()=>database({insurance_requests:requests,activity_logs:activities},1,failure)}});return getNotificationSummary({role:'agent',userId:'agent-a'});}
const old=new Date(Date.now()-2*3600000).toISOString(),now=new Date().toISOString();
test('audit bell: assigned waiting-payment does not appear as an actionable alert',async()=>assert.deepEqual(await summary([{id:'a',status:'waiting_payment',assigned_agent_id:'agent-a',assigned_at:old,created_at:old}]),{count:0,level:'none',renewalCount:0}));
test('audit bell: WhatsApp activity does not hide an active preparation',async()=>assert.equal((await summary([{id:'a',status:'policy_preparation',assigned_agent_id:'agent-a',assigned_at:old,created_at:old}],[{id:'log',request_id:'a',action:'policy_whatsapp_sent',created_at:now}])).count,1));
test('audit bell: recent assignment resets urgency and all pages are counted',async()=>assert.deepEqual(await summary(['a','b'].map(id=>({id,status:'policy_preparation',assigned_agent_id:'agent-a',assigned_at:now,created_at:old}))),{count:2,level:'watch',renewalCount:0}));
test('audit bell: database outage is distinct from no notifications',async()=>assert.equal((await summary([],[],'Test outage')).level,'unavailable'));
for(const role of ['agent','admin'])test('audit mutation: reassignment race preserves role authorization '+role,async()=>{
 const state={id:'request-test',status:'payment_confirmed',assigned_agent_id:'agent-a'};
 const db={from(){let updating=null;const filters=[];const q=new Proxy({then(resolve){if(!updating){const snapshot={...state};state.assigned_agent_id='agent-b';return Promise.resolve({data:snapshot,error:null}).then(resolve);}const matches=filters.every(([k,v])=>state[k]===v);if(matches)Object.assign(state,updating);return Promise.resolve({data:matches?{id:state.id}:null,error:null}).then(resolve);}},{get(o,k){if(k in o)return o[k];if(k==='update')return v=>{updating=v;return q};if(k==='eq')return(k,v)=>{filters.push([k,v]);return q};return()=>q}});return q}};
 const {POST}=loadTs('app/api/admin/requests/[id]/status/route.ts',{'@/lib/supabase/service':{createServiceClient:()=>db},'@/lib/supabase/server':{createServerSupabaseClient:async()=>({auth:{getUser:async()=>({data:{user:{id:'agent-a',app_metadata:{role}}},error:null})}})},'@/lib/insurance/quoteSchema':{hasQuoteSchema:async()=>false},'@/lib/activity/logActivity':{logActivity:async()=>{}}});
 const response=await POST(new Request('http://test.local/status',{method:'POST',body:JSON.stringify({action:'cancel_request'})}),{params:Promise.resolve({id:'request-test'})});
 assert.equal(response.status,role==='agent'?409:200);assert.equal(state.status,role==='agent'?'payment_confirmed':'cancelled');assert.equal(state.assigned_agent_id,'agent-b');
});
