const {PGlite}=require('@electric-sql/pglite');const {unaccent}=require('@electric-sql/pglite/contrib/unaccent');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const schema=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/document-workflow-schema.json')));
(async()=>{const db=new PGlite({extensions:{unaccent}});try{
 await db.exec('create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,raw_app_meta_data jsonb);');
 for(const [table,def] of Object.entries(schema)){const cols=Object.entries(def.properties).map(([name,v])=>{let defaults=name==='id'?(v.format==='bigint'?' generated by default as identity':' default gen_random_uuid()'):v.default!==undefined?' default '+(v.default==='now()'?'now()':typeof v.default==='boolean'?String(v.default):"'"+String(v.default).replaceAll("'","''")+"'"):'';return '"'+name+'" '+v.format+(name==='id'?' primary key':'')+defaults+(def.required.includes(name)?' not null':'');});await db.exec('create table '+table+'('+cols.join(',')+');');}
 await db.exec('alter table insurance_requests add column client_snapshot jsonb; alter table uploaded_documents add unique(request_id,document_type);');
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260930135042_direct_request_deduplication.sql'),'utf8'));
 const client={first_name:'IVAN',last_name:'EXEMPLE',father_name:'TEST',birth_date:'2000-01-01',gender:'male',nationality:'Cameroun',whatsapp_country_code:'+90',whatsapp_number:'5550000000',province_id:1,district_id:1,neighborhood_id:1,street:'Test Sokak',building_number:'4',apartment_number:null};
 const request={preferred_language:'fr',has_kimlik:false,kimlik_number:null,kimlik_expiration_date:null,passport_number:'TEST123',insurance_start_date:'2026-10-01',insurance_duration_years:1,calculated_age:26,calculated_price:600};
 async function create(c={},r={},documents=null){const id=crypto.randomUUID();return (await db.query('select create_direct_request($1,$2,null,$3,$4) as result',[id,JSON.stringify({...client,...c}),JSON.stringify({...request,request_code:'IF-'+id,...r}),JSON.stringify(documents??[{document_type:'passport',storage_path:id+'/passport/test.pdf',original_file_name:'test.pdf',mime_type:'application/pdf',file_size:100}])])).rows[0].result;}
 const first=await create();assert.equal(first.reused,false);
 const again=await create({first_name:' ivan ',street:'  test   sokak ',apartment_number:''},{preferred_language:'en',calculated_price:999});assert.equal(again.reused,true);assert.equal(again.requestId,first.requestId);assert.equal(again.calculatedPrice,600);
 assert.equal((await db.query('select count(*)::int as n from insurance_requests')).rows[0].n,1);
 assert.equal((await db.query('select count(*)::int as n from clients')).rows[0].n,1);
 assert.equal((await db.query('select count(*)::int as n from uploaded_documents')).rows[0].n,1);
 assert.equal((await db.query('select count(*)::int as n from activity_logs')).rows[0].n,1);
 // Repeated submissions never extend the original ten-minute window.
 const before=(await db.query('select created_at from insurance_requests where id=$1',[first.requestId])).rows[0].created_at;
 await create();assert.equal((await db.query('select created_at from insurance_requests where id=$1',[first.requestId])).rows[0].created_at.getTime(),before.getTime());
 await db.query("update insurance_requests set created_at=clock_timestamp()-interval '9 minutes 59 seconds' where id=$1",[first.requestId]);assert.equal((await create()).reused,true);
 await db.query("update insurance_requests set created_at=clock_timestamp()-interval '10 minutes 1 second' where id=$1",[first.requestId]);const later=await create();assert.equal(later.reused,false);assert.notEqual(later.requestId,first.requestId);
 for(const [c,r] of [[{whatsapp_number:'5550000001'},{}],[{street:'Other Sokak'},{}],[{}, {insurance_duration_years:2}],[{}, {passport_number:'OTHER'}],[{}, {insurance_start_date:'2026-10-02'}]])assert.equal((await create(c,r)).reused,false);
 await db.query("update insurance_requests set status='payment_review' where id=$1",[later.requestId]);const paid=await create();assert.equal(paid.requestId,later.requestId);assert.equal(paid.status,'payment_review');
 await db.query("update insurance_requests set status='cancelled' where id=$1",[later.requestId]);const replacement=await create();assert.equal(replacement.reused,false);
 // Already-created dossiers without fingerprints also match (no backfill or rewriting history).
 await db.query('update insurance_requests set submission_fingerprint=null where id=$1',[replacement.requestId]);assert.equal((await create()).requestId,replacement.requestId);
 await db.query('update insurance_requests set client_snapshot=null where id=$1',[replacement.requestId]);assert.equal((await create()).requestId,replacement.requestId);
 // Atomic failure leaves neither a client nor a dossier behind.
 const counts=async()=>(await db.query('select (select count(*)::int from clients) as clients,(select count(*)::int from insurance_requests) as requests')).rows[0];const baseline=await counts();
 await db.exec("create function fail_doc() returns trigger language plpgsql as $$begin raise exception 'test failure';end$$;create trigger fail_doc before insert on uploaded_documents for each row execute function fail_doc();");
 await assert.rejects(()=>create({first_name:'FAILURE'}));assert.deepEqual(await counts(),baseline);await db.exec('drop trigger fail_doc on uploaded_documents;drop function fail_doc();');
 const kimlik={has_kimlik:true,kimlik_number:'99000000000',kimlik_expiration_date:'2027-01-01'};
 await assert.rejects(()=>create({first_name:'KIMLIK'},kimlik),e=>e.code==='22023');assert.deepEqual(await counts(),baseline);
 const concurrent=await Promise.all([create({first_name:'PARALLEL'}),create({first_name:'PARALLEL'})]);assert.equal(concurrent[0].requestId,concurrent[1].requestId);assert.equal(concurrent.filter(r=>!r.reused).length,1);
 for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_function_privilege($1,'create_direct_request(uuid,jsonb,uuid,jsonb,jsonb)','execute') as ok",[role])).rows[0].ok,false);
 assert.equal((await db.query("select has_function_privilege('service_role','create_direct_request(uuid,jsonb,uuid,jsonb,jsonb)','execute') as ok")).rows[0].ok,true);
 console.log('Direct request dedup: normalized identity, exact ten-minute window, original price, changed data, cancelled/paid status, legacy requests, atomic rollback, repeated submissions and role gates passed.');
 }finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
