const test=require('node:test'),assert=require('node:assert/strict');const {loadTs}=require('./load-ts.cjs');
function api({reused=false,rpcError=null}={}){
 const calls={copies:0,removes:0,rpc:[]};
 const db={from(){const q={select(){return q;},eq(){return q;},neq(){return q;},order(){return q;},limit(){return q;},maybeSingle:async()=>({data:null,error:null}),then(resolve){resolve({data:[],error:null});},insert(){throw Error('Creation must be atomic');},delete(){throw Error('Never delete an uncertain committed request');}};return q;},rpc:async(name,args)=>{calls.rpc.push({name,args});return {data:rpcError?null:{success:true,reused,requestId:reused?'original':args.p_request_id,requestCode:'IF-ORIGINAL',calculatedPrice:600,calculatedAge:26,status:'waiting_payment'},error:rpcError};},storage:{from(){return {copy:async()=>{calls.copies++;return {error:null};},remove:async()=>{calls.removes++;return {error:null};}};}}};
 const route=loadTs('app/api/requests/route.ts',{'@/lib/supabase/service':{createServiceClient:()=>db},'@/lib/insurance/quoteSchema':{hasQuoteSchema:async()=>true},'@/lib/security/rateLimit':{consumeRateLimit:async()=>({allowed:true}),getClientIp:()=> 'TEST'},'@/lib/insurance/calculatePriceServer':{calculateInsurancePriceServer:async()=>({available:true,price:600,age:26})},'@/lib/security/verifyStoredDocument':{verifyStoredDocument:async()=>({fileSize:100,mimeType:'application/pdf'})},'@/lib/insurance/prepareDocumentCopy':{prepareDocumentCopy:async()=>{}},'@/lib/activity/logActivity':{logActivity:async()=>{throw Error('Creation log belongs in transaction');}}});
 const session=crypto.randomUUID();const payload={firstName:'IVAN',lastName:'TEST',fatherName:'TEST',birthDate:'2000-01-01',gender:'male',nationality:'Cameroun',whatsappCountryCode:'+90',whatsappNumber:'5550000000',hasKimlik:false,passportNumber:'TEST123',insuranceStartDate:'2099-01-01',duration:1,address:{provinceId:'1',districtId:'1',neighborhoodId:'1',street:'Test',buildingNumber:'1',apartmentNumber:''},preferredLanguage:'fr'};
 return {calls,run:()=>route.POST(new Request('http://localhost',{method:'POST',body:JSON.stringify({payload,uploadSessionId:session,documents:[{documentType:'passport',storagePath:`pending/${session}/passport/test.pdf`,originalFileName:'test.pdf',mimeType:'application/pdf',fileSize:100}]})}))};
}
test('Identical request returns original dossier with reused flag and no independent inserts',async()=>{const a=api({reused:true}),r=await a.run();assert.equal(r.status,200);assert.equal((await r.json()).requestId,'original');assert.equal(a.calls.rpc[0].name,'create_direct_request');assert.equal(a.calls.removes,0);});
test('New direct request uses atomic creation and returns 201',async()=>{const a=api(),r=await a.run();assert.equal(r.status,201);assert.equal((await r.json()).reused,false);assert.equal(a.calls.rpc.length,1);});
test('Uncertain atomic response never deletes copied files or a committed dossier',async()=>{const a=api({rpcError:{code:'08006'}}),r=await a.run();assert.equal(r.status,500);assert.equal(a.calls.copies,1);assert.equal(a.calls.removes,0);});
