const test=require('node:test'),assert=require('node:assert/strict');const {loadTs}=require('./load-ts.cjs');
const requestId='10000000-0000-4000-8000-000000000010',paymentId='10000000-0000-4000-8000-000000000011',actor='10000000-0000-4000-8000-000000000001',operationId='10000000-0000-4000-8000-000000000012';
const body={action:'confirm_payment',paymentId,paymentSubmittedAt:'2026-09-17T09:00:00Z',operationId};
function route({role='agent',user=true,error=null}={}){const calls=[];const db={from(){throw Error('Payment decision must not use separate writes')},rpc:async(name,payload)=>{calls.push({name,payload});return {error,data:error?null:{success:true,action:payload.p_action,status:payload.p_action==='confirm_payment'?'payment_confirmed':'payment_rejected'}}}};const {POST}=loadTs('app/api/admin/requests/[id]/status/route.ts',{'@/lib/supabase/service':{createServiceClient:()=>db},'@/lib/supabase/server':{createServerSupabaseClient:async()=>({auth:{getUser:async()=>({data:{user:user?{id:actor,app_metadata:{role}}:null},error:null})}})}});return {calls,run:(data=body)=>POST(new Request('http://test.local',{method:'POST',body:JSON.stringify(data)}),{params:Promise.resolve({id:requestId})})};}
test('payment decision API: one RPC with actor, operation and displayed submission version',async()=>{const r=route();const response=await r.run();assert.equal(response.status,200);assert.deepEqual(r.calls,[{name:'decide_payment',payload:{p_request_id:requestId,p_payment_id:paymentId,p_submitted_at:body.paymentSubmittedAt,p_action:'confirm_payment',p_reason:'',p_actor:actor,p_operation_id:operationId}}]);assert.equal(response.headers.get('cache-control'),'no-store');});
test('payment decision API: refusal preserves reason and uses same transaction',async()=>{const r=route();assert.equal((await r.run({...body,action:'reject_payment',rejectionReason:' Montant incorrect '})).status,200);assert.equal(r.calls[0].payload.p_reason,'Montant incorrect');});
test('payment decision API: malformed or unversioned actions never call database',async()=>{for(const data of [null,{}, {action:'confirm_payment'},{...body,operationId:'bad'},{...body,paymentSubmittedAt:undefined},{...body,action:'reject_payment',rejectionReason:3}]){const r=route();assert.equal((await r.run(data)).status,400);assert.equal(r.calls.length,0);}});
test('payment decision API: session and role gate still protect decisions',async()=>{for(const [options,status] of [[{user:false},401],[{role:'partner'},403]]){const r=route(options);assert.equal((await r.run()).status,status);assert.equal(r.calls.length,0);}});
test('payment decision API: transaction failures retain meaningful status and no fallback writes',async()=>{for(const [code,status] of [['42501',403],['P0002',404],['40001',409],['22023',400],['PGRST202',503],['42883',503],['XX000',500]]){const r=route({error:{code,message:'simulated'}});assert.equal((await r.run()).status,status);assert.equal(r.calls.length,1);}});
