const {PGlite}=require('@electric-sql/pglite');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const schema=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/payment-decision-schema.json')));
const migration=fs.readFileSync(path.join(__dirname,'../supabase/migrations/202609170003_payment_decisions_atomic.sql'),'utf8');
const agent='10000000-0000-4000-8000-000000000001',other='10000000-0000-4000-8000-000000000002',admin='10000000-0000-4000-8000-000000000003',partner='10000000-0000-4000-8000-000000000004';
const submitted='2026-09-17T09:00:00.000Z';
(async()=>{const db=new PGlite();try{
 await db.exec('create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,raw_app_meta_data jsonb);');
 for(const [table,def] of Object.entries(schema)){const cols=Object.entries(def.properties).map(([name,v])=>`"${name}" ${v.format}${name==='id'?' primary key default gen_random_uuid()':name==='created_at'||name==='updated_at'?' default now()':''}${def.required.includes(name)&&name!=='id'?' not null':''}`);await db.exec(`create table ${table}(${cols.join(',')});`);}
 for(const [id,role] of [[agent,'agent'],[other,'agent'],[admin,'admin'],[partner,'partner']])await db.query('insert into auth.users values($1,$2)',[id,JSON.stringify({role})]);
 await db.exec(migration);const results=[];
 async function seed(owner=agent,stamp=submitted){const request=crypto.randomUUID(),payment=crypto.randomUUID();await db.query("insert into insurance_requests(id,request_code,client_id,passport_number,insurance_duration_years,calculated_age,calculated_price,status,has_kimlik,preferred_language,source,assigned_agent_id) values($1,$2,$3,'FAKE',1,25,525,'payment_review',false,'fr','direct',$3)",[request,'EXAMPLE-'+request,owner||agent]);if(owner===null)await db.query('update insurance_requests set assigned_agent_id=null where id=$1',[request]);await db.query("insert into payments(id,request_id,payment_method,expected_amount,status,submitted_at) values($1,$2,'bank_transfer',525,'submitted',$3)",[payment,request,stamp]);return {request,payment,stamp,op:crypto.randomUUID()};}
 const call=async(item,{actor=agent,action='confirm_payment',reason='',op=item.op,stamp=item.stamp}={})=>(await db.query('select decide_payment($1,$2,$3,$4,$5,$6,$7) as result',[item.request,item.payment,stamp,action,reason,actor,op])).rows[0].result;
 const state=async item=>(await db.query('select r.status as request_status,p.status as payment_status,p.verified_at,p.verified_by,p.rejection_reason from insurance_requests r join payments p on p.request_id=r.id where r.id=$1',[item.request])).rows[0];
 const count=async(table,item)=>(await db.query(`select count(*)::int as n from ${table} where request_id=$1`,[item.request])).rows[0].n;
 const confirmed=await seed();const first=await call(confirmed);assert.equal(first.status,'payment_confirmed');const cs=await state(confirmed);assert.equal(cs.payment_status,'confirmed');assert.equal(cs.verified_by,agent);assert.ok(cs.verified_at);assert.equal(await count('activity_logs',confirmed),1);results.push('Confirmation : paiement, dossier, auteur et historique adoptés ensemble');
 assert.deepEqual(await call(confirmed),first);assert.equal(await count('activity_logs',confirmed),1);assert.equal(await count('payment_decision_operations',confirmed),1);results.push('Même opération rejouée : même résultat sans deuxième historique');
 await db.query("update insurance_requests set status='policy_preparation' where id=$1",[confirmed.request]);assert.deepEqual(await call(confirmed),first);assert.equal((await state(confirmed)).request_status,'policy_preparation');results.push('Réponse perdue puis progression du dossier : la répétition ne remet pas le statut en arrière');
 await assert.rejects(()=>call(confirmed,{action:'reject_payment',reason:'Autre décision'}),e=>e.code==='40001');results.push('Même clé avec décision différente refusée');
 const rejected=await seed();await call(rejected,{action:'reject_payment',reason:' Montant incorrect '});const rs=await state(rejected);assert.equal(rs.request_status,'payment_rejected');assert.equal(rs.payment_status,'rejected');assert.equal(rs.rejection_reason,'Montant incorrect');results.push('Refus : motif normalisé et deux statuts cohérents');
 const reassigned=await seed();await db.query('update insurance_requests set assigned_agent_id=$1 where id=$2',[other,reassigned.request]);await assert.rejects(()=>call(reassigned),e=>e.code==='42501');assert.equal((await state(reassigned)).request_status,'payment_review');assert.equal(await count('activity_logs',reassigned),0);results.push('Ancien agent refusé après réattribution sans aucune écriture');
 await call(reassigned,{actor:admin});results.push('Administrateur conserve le droit de valider un dossier attribué ailleurs');
 const free=await seed(null);await assert.rejects(()=>call(free),e=>e.code==='42501');await call(free,{actor:admin});results.push('Dossier non attribué : agent refusé et admin autorisé');
 const changed=await seed();await db.query('update payments set submitted_at=$1 where id=$2',['2026-09-17T10:00:00Z',changed.payment]);await assert.rejects(()=>call(changed),e=>e.code==='40001');assert.equal((await state(changed)).payment_status,'submitted');results.push('Nouveau justificatif : décision de l’ancien écran refusée');
 const failure=await seed();await db.exec("create function fail_payment_test() returns trigger language plpgsql as $$begin raise exception 'simulated payment failure';end$$;create trigger payment_test before update on payments for each row execute function fail_payment_test();");await assert.rejects(()=>call(failure));await db.exec('drop trigger payment_test on payments;drop function fail_payment_test();');assert.equal((await state(failure)).request_status,'payment_review');assert.equal((await state(failure)).payment_status,'submitted');assert.equal(await count('activity_logs',failure),0);assert.equal(await count('payment_decision_operations',failure),0);results.push('Échec paiement après modification dossier : rollback intégral');
 await db.exec("create function fail_log_test() returns trigger language plpgsql as $$begin raise exception 'simulated log failure';end$$;create trigger log_test before insert on activity_logs for each row execute function fail_log_test();");await assert.rejects(()=>call(failure));await db.exec('drop trigger log_test on activity_logs;drop function fail_log_test();');assert.equal((await state(failure)).request_status,'payment_review');assert.equal((await state(failure)).payment_status,'submitted');results.push('Échec historique : ni dossier ni paiement partiellement validé');
 await call(failure);results.push('Après interruption, la même opération peut réussir une seule fois');
 const conflict=await seed();await call(conflict,{action:'reject_payment',reason:'Refus',op:crypto.randomUUID()});await assert.rejects(()=>call(conflict),e=>e.code==='40001');assert.equal((await state(conflict)).payment_status,'rejected');results.push('Décisions concurrentes opposées : la première adoptée reste protégée');
 const forbidden=await seed();await assert.rejects(()=>call(forbidden,{actor:partner}),e=>e.code==='42501');await assert.rejects(()=>call(forbidden,{action:'reject_payment',reason:' '}),e=>e.code==='22023');results.push('Rôle partenaire et refus sans motif interdits');
 const legacy=await seed(agent,null);await call(legacy);results.push('Ancien paiement soumis sans date conservé compatible');
 for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(()=>call(forbidden),e=>e.code==='42501');await assert.rejects(()=>db.query('select * from payment_decision_operations'),e=>e.code==='42501');await db.exec('reset role');}results.push('Fonction et journal privés pour les rôles ordinaires');
 await db.exec('grant all on all tables in schema public to service_role;set role service_role;');await call(forbidden);await db.exec('reset role');results.push('Exécution serveur autorisée avec rôle réel de l’acteur vérifié');
 console.log(JSON.stringify(results,null,2));
 }finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1});
