const test=require('node:test'),assert=require('node:assert/strict');const {loadTs}=require('./load-ts.cjs');
const {calculateInsuranceAge}=loadTs('lib/validation/date.ts'),{requestSnapshot}=loadTs('lib/clients/requestSnapshot.ts'),{accounting,historicalRequests}=loadTs('lib/accounting/model.ts');
test('Business date uses Istanbul at the UTC year boundary',()=>{assert.equal(calculateInsuranceAge('2000-01-01',new Date('2026-12-31T21:30:00Z')),27);assert.equal(calculateInsuranceAge('2027-01-01',new Date('2026-12-31T21:30:00Z')),0);assert.equal(calculateInsuranceAge('2027-01-02',new Date('2026-12-31T21:30:00Z')),null);});
test('Dossier snapshot keeps new contact details without changing shared identity or IDs',()=>{const client={id:'shared',first_name:'TEST',whatsapp_number:'old'};const result=requestSnapshot(client,{id:'OTHER',whatsapp_number:'new',street:'TEST'});assert.equal(result.id,'shared');assert.equal(result.whatsapp_number,'new');assert.equal(client.whatsapp_number,'old');assert.equal(requestSnapshot(client,null),client);});
test('Historical insurer balance uses the status then and never fabricates history before capture',()=>{const snapshot={id:'r',request_code:'TEST',insurance_company_id:'a',status:'policy_available',actual_insurance_cost:100,insurance_company_selected_at:'2026-09-17'};const data={companies:[],rates:[],deposits:[{insurance_company_id:'a',amount:1000,deposit_date:'2026-09-01'}],withdrawals:[],requests:[{...snapshot,status:'cancelled'}],payments:[],history:[],authors:{},loadedAt:'2026-09-20',captureStartedAt:'2026-09-17T09:00:00Z',requestEvents:[{request_id:'r',captured_at:'2026-09-17T10:00:00Z',event_type:'baseline',snapshot},{request_id:'r',captured_at:'2026-09-19T10:00:00Z',event_type:'change',snapshot:{...snapshot,status:'cancelled'}}]};assert.equal(accounting(data,{from:'',to:'2026-09-18',company:'a'}).balance,90000);assert.equal(accounting(data,{from:'',to:'2026-09-20',company:'a'}).balance,100000);assert.equal(accounting(data,{from:'',to:'2026-09-16',company:'a'}).balance,null);assert.equal(historicalRequests(data,'2026-09-18')[0].status,'policy_available');});

function receiptAPI({phone='061234567',prior=null,schemaError=false,rpcError=null,actualSize=100}={}){
 const calls={copy:0,verify:0,rpc:[],prepared:0};const id='10000000-0000-4000-8000-000000000001';
 const db={from(table){const q={select(){return q;},eq(){return q;},maybeSingle:async()=>({data:table==='insurance_requests'?{id,request_code:'TEST',source:'direct',partner_id:null,client:{whatsapp_country_code:'+242',whatsapp_number:phone}}:prior,error:table==='workflow_operations'&&schemaError?{code:'PGRST205'}:null})};return q;},rpc:async(name,args)=>{calls.rpc.push({name,args});return {data:rpcError?null:{success:true,status:'payment_review'},error:rpcError};},storage:{from(){return {copy:async()=>{calls.copy++;return {error:null};},remove:()=>{throw Error('An uncertain adoption must not delete storage.');}};}}};
 const {submitReceipt}=loadTs('lib/insurance/submitReceipt.ts',{'@/lib/supabase/service':{createServiceClient:()=>db},'@/lib/security/rateLimit':{getClientIp:()=> 'EXAMPLE',consumeRateLimit:async()=>({allowed:true,remaining:1,retryAfterSeconds:0})},'@/lib/security/verifyStoredDocument':{verifyStoredDocument:async()=>{calls.verify++;return {mimeType:'application/pdf',fileSize:actualSize};}},'@/lib/insurance/prepareDocumentCopy':{prepareDocumentCopy:async()=>{calls.prepared++;}},'@/lib/notifications/processOutbox':{processOutbox:async()=>({sent:0,failed:0})}});
 const body={requestCode:'TEST',whatsappCountryCode:'+242',whatsappNumber:'061234567',path:'pending/direct/payment/'+id+'/test.pdf',originalFileName:'test.pdf',mimeType:'application/pdf',fileSize:100};
 return {calls,run:(extra={})=>submitReceipt(new Request('http://localhost',{method:'POST',body:JSON.stringify({...body,...extra})}),{id})};
}
test('Receipt adoption authenticates the current dossier before touching private storage',async()=>{const api=receiptAPI({phone:'OTHER'});assert.equal((await api.run()).status,403);assert.equal(api.calls.copy,0);assert.equal(api.calls.verify,0);assert.equal(api.calls.rpc.length,0);});
test('Receipt retry returns the stored result without moving or resending anything',async()=>{const api=receiptAPI({prior:{actor_id:null,payload:{original_file_name:'test.pdf',mime_type:'application/pdf',file_size:100},result:{success:true,status:'payment_review'}}});assert.equal((await api.run()).status,200);assert.equal(api.calls.copy,0);assert.equal(api.calls.verify,0);assert.equal(api.calls.rpc.length,0);});
test('Missing receipt migration fails before copying a document',async()=>{const api=receiptAPI({schemaError:true});assert.equal((await api.run()).status,503);assert.equal(api.calls.copy,0);assert.equal(api.calls.rpc.length,0);});
test('Receipt metadata must match the actual private file',async()=>{const api=receiptAPI({actualSize:101});assert.equal((await api.run()).status,400);assert.equal(api.calls.copy,0);});
test('Uncertain receipt save keeps the prepared copy and reports failure',async()=>{const api=receiptAPI({rpcError:{code:'08006'}});assert.equal((await api.run()).status,500);assert.equal(api.calls.copy,1);assert.equal(api.calls.prepared,1);assert.equal(api.calls.rpc.length,1);assert.equal(api.calls.rpc[0].name,'submit_payment_receipt');assert.equal(api.calls.rpc[0].args.p_actor_id,null);});
test('WhatsApp failure remains in the durable queue without automatic uncertain retries',async()=>{const finishes=[];const db={rpc:async(name,args)=>name==='claim_notifications'?{data:[{id:'TEST',lease_token:'TOKEN',template:'policy_available',payload:{phoneNumber:'EXAMPLE',matricule:'TEST'}}],error:null}:(finishes.push(args),{data:true,error:null})};const {processOutbox}=loadTs('lib/notifications/processOutbox.ts',{'@/lib/supabase/service':{createServiceClient:()=>db},'@/lib/whatsapp/sendWhatsAppMessage':{sendWhatsAppMessage:async()=>{throw Error('Provider response lost');},sendPartnerWhatsAppMessage:async()=>{throw Error('unused');}}});assert.deepEqual(await processOutbox(),{sent:0,failed:1});assert.equal(finishes[0].p_retry,false);assert.equal(finishes[0].p_token,'TOKEN');assert.ok(finishes[0].p_error);});
